Resources:
  RDSProxyIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: rds.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: rds-proxy-policy-${self:provider.stage}-${self:service}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource:
                - Ref: SecretPostgresMasterUserPassword
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
              - Resource: ${self:custom.environment.KMS_CERTIFICATE_ARN}
                Effect: Allow
                Action:
                  - kms:Decrypt