Resources:
  # -------------------------------------------------
  # 1. IAM Role – KMS Administrator
  # -------------------------------------------------
  KmsAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:provider.stage}-kms-key-enp-Role-Admin
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root   # change if needed
            Action: sts:AssumeRole
      # Optional: attach any managed policies you want
      # ManagedPolicyArns:
      #   - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      # Tags:
      #   - Key: ResourceName
      #     Value: ${self:provider.stage}-kms-admin-role
      #   - Key: Environment
      #     Value: ${self:provider.stage}
      #   - Key: ProjectNamespace
      #     Value: ${self:custom.namespace}

  # -------------------------------------------------
  # 2. KMS Key (depends on role existing first)
  # -------------------------------------------------
  KeyPostgres:
    Type: AWS::KMS::Key
    DependsOn: KmsAdminRole
    Properties:
      Description: KMS key for Postgres credentials (Secrets Manager + RDS)
      Enabled: true
      EnableKeyRotation: true
      KeyUsage: ENCRYPT_DECRYPT
      PendingWindowInDays: 7
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowRoot
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

          - Sid: AllowServices
            Effect: Allow
            Principal:
              Service:
                - secretsmanager.amazonaws.com
                - rds.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: '*'

          - Sid: AllowKmsAdminRole
            Effect: Allow
            Principal:
              AWS: !GetAtt KmsAdminRole.Arn
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:List*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
              - kms:TagResource
              - kms:UntagResource
            Resource: '*'

      Tags:
        - Key: ResourceName
          Value: ${self:provider.stage}-postgres-kms
        - Key: ProjectNamespace
          Value: ${self:custom.namespace}
        - Key: Environment
          Value: ${self:provider.stage}

  # -------------------------------------------------
  # 3. KMS Alias
  # -------------------------------------------------
  KeyPostgresAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${self:provider.stage}-postgres-credentials
      TargetKeyId: !Ref KeyPostgres

  SecretPostgresMasterUserPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:provider.stage}/rds/postgres
      Description: 'Username and password for the shared enp postgres database administrator account'
      KmsKeyId: ${self:custom.environment.KMS_CERTIFICATE_ID}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludePunctuation: true    

Outputs:
  KmsKeyArn:
    Value: !GetAtt KeyPostgres.Arn
    Export:
      Name: ${self:provider.stage}-postgres-kms-key-arn

  KmsKeyAlias:
    Value: !Ref KeyPostgresAlias

  KmsAdminRoleArn:
    Value: !GetAtt KmsAdminRole.Arn
    Export:
      Name: ${self:provider.stage}-kms-admin-role-arn