Resources:
  S3DownloadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.environment.DOWNLOAD_BUCKET_NAME}

  S3BucketApp:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.environment.APPLICATION_BUCKET_NAME}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain     
  
      

  