Resources:
  CloudFrontARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: ${self:custom.environment.HOSTED_ZONE_ID_DOMAIN}  # your hosted zone ID
      Name: ${self:custom.environment.APPLICATION_CUSTOM_DOMAIN_NAME} # e.g., stg-econet-plateau.net
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2       # CloudFront hosted zone ID
        DNSName: !GetAtt PublicDistribution.DomainName

Outputs:
  CloudFrontARecordOutput:
    Description: Record set name for CloudFront
    Value: !Ref CloudFrontARecord
    Export:
      Name: ${self:provider.stage}-CloudFrontARecord
